babi.py

This is a command to write to the file. User can do `:w` to save alongside <kbd>ctrl+s</kbd>

:w command

---

babi.py
tests/babi_test.py

This command will write to the current file and then close the editor a la Vim

:wq command

---

.pre-commit-config.yaml
setup.cfg
tests/features/conftest.py

[python 3 statement - 3.6.0](https://github.com/asottile/scratch/wiki/python-3-statement#360)
(due to broken `NamedTuple` in 3.6.0)

babi: require 3.6.1+

---

babi/screen.py

I fixed the windows key codes in wch.

Fixed windows keys

---

babi/screen.py

Ps key fix

---

babi/screen.py

Now you can use the enter key on the numpad as well. 
tested on Windows.

add numpad enter

---

babi/screen.py

fix fullscreen on macos in Terminal

---

azure-pipelines.yml

re-enable pypy3 testing

---

babi/main.py

fix race condition with ^Z on close

---

babi/highlight.py
tests/highlight_test.py

fix highlighting hang with empty begin end rules

---

babi/file.py
tests/features/comment_test.py

This hopefully will fix #95.
Fingers crossed.

fix whitespace on added comment

---

README.md

Add video explaining babi vs nano

---

babi/file.py
tests/features/text_editing_test.py

fix backspacing an extra blank line at end of file

---

babi/hl/syntax.py
setup.cfg

Committed via https://github.com/asottile/all-repos

stricter mypy settings

---

babi/hl/syntax.py

A_ITALIC is not always present unlike what's documented

---

babi/screen.py
tests/features/replace_test.py

Handle errors when replacing

---

babi/cached_property.py
babi/screen.py

Committed via https://github.com/asottile/all-repos

improve coverage pragmas with covdefaults 2.1

---

babi/screen.py
tests/features/save_test.py

Resolved #180, babi can now save to directories that doesn't exist before.

---

babi/screen.py
tests/features/save_test.py

Revert "Revert "Merge pull request #181 from ClasherKasten/feature/issue-180""
This reverts commit c4853f26e433f61493ee4e68de9eb3f10fc8f47e.
Tried to clean up git a second time.
I just did like you mentioned in my last PR, but to name my branch the same i had to delete the `origin/issues_180_and_183` branch and create it new. I don't know if this would be unnecessary.

Fixing issues #180 and #183

---

babi/highlight.py
tests/highlight_test.py

highlight syntax in executable files without file-extensions

---

babi/highlight.py
babi/theme.py

weird, I probably should have [watched my own video](https://youtu.be/sVjtp6tGo0g) lol

fix memory leak in :retheme

---

README.md
babi/file.py
tests/features/movement_test.py

Removed unnecessary if-statement. Added key-combo to README.
Closes #218.

Fixed M-Up breaks when first line is empty. 

---

README.md

Installation instruction is extended.

Extend installation description

---

babi/screen.py

disable SIGQUIT handler when exiting raw mode

---

babi/file.py
tests/features/replace_test.py

skip replacing on the last "fake" line of the file

---

README.md

And `s/comment on/comment out`

document the tabsize command

---

.github/workflows/main.yml

This reverts commit 7dc7abdb5c19df40d1d2ce514ed9ad253d39937a.

Revert "temporarily avoid broken tmux by using 20.04"

---

setup.cfg

see also https://github.com/zephyrproject-rtos/windows-curses/issues/41

ban broken version of windows-curses

---

babi/file.py
tests/features/save_test.py

forbid opening files that contain null bytes

---

babi/file.py
babi/screen.py
tests/features/save_test.py

don't crash while saving over non-utf-8 file

---

babi/linters/pre_commit.py
tests/linters/pre_commit_test.py

use the correct pre-commit config

---

babi/file.py
tests/features/conftest.py
tests/features/cut_uncut_test.py

fix eof invariant when cutting selection to end of file
